# Generated by Django 3.0.2 on 2020-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('A', 'action'), ('D', 'drama'), ('C', 'comedy'), ('R', 'romance')], max_length=150)),
                ('slug', models.SlugField()),
                ('year_production', models.DateField()),
                ('image', models.ImageField(upload_to='movies/')),
                ('language', models.CharField(choices=[('A', 'arabic'), ('E', 'english'), ('G', 'german'), ('C', 'chinese')], max_length=150)),
                ('status', models.CharField(choices=[('RA', 'recently added'), ('mv', 'most viewed'), ('TR', 'top rated')], max_length=150)),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
