# Generated by Django 3.0.2 on 2020-05-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200506_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
    ]
