# Generated by Django 3.0.2 on 2020-05-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_participant_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
