# Generated by Django 3.0.2 on 2020-05-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_participant_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.Participant'),
        ),
    ]
