# Generated by Django 3.0.2 on 2020-05-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200506_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='movie.Movie'),
        ),
    ]
