# Generated by Django 3.0.2 on 2020-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
