# Generated by Django 3.0.2 on 2020-05-07 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_movie_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 14, 10, 43, 740407)),
        ),
    ]
